services:
  local_db:
    build:
      context: images
      dockerfile: MySQL_Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - vcupload_sqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 15s
      timeout: 10s
      retries: 10

  front:
    build:
      context: images
      dockerfile: Nuxt_Dockerfile
    volumes:
      - ../front:/app
    ports:
      - "3000:3000"

  back:
    build:
      context: ../
      dockerfile: docker/images/Back_Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      local_db:
        condition: service_healthy
    volumes:
      - ../back/files:/app/files

volumes:
  vcupload_sqldata: